### ISSUE TITLE
Issue Downloading DSMIL WSI Tests

### ISSUE THREAD

**Issue by bryanwong17** [GeorgeBatch/TCGA_lung#2]
Hi @GeorgeBatch, while running the command bash `./0-download-LUSC-and-LUAD.sh`, I encountered an issue where the WSI used for testing in DSMIL are not being downloaded. According to the documentation, the list of these files is specified in `dsmil-split/google-drive/TEST_ID.csv`. Could you confirm if this is expected behavior? If so, please provide guidance on how to download the necessary testing dataset. Thank you!

**Comment by GeorgeBatch** [comment]
Hi @bryanwong17!

[./0-download-LUSC-and-LUAD.sh](https://github.com/GeorgeBatch/TCGA-lung-histology-download/blob/main/0-download-LUSC-and-LUAD.sh) does not use `dsmil-split/google-drive/TEST_ID.csv`. It uses the manifest files inside the [./tcga-download/](https://github.com/GeorgeBatch/TCGA-lung-histology-download/blob/main/tcga-download/). So all TCGA files that you specify in the manifests should be downloaded.

If running [./0-download-LUSC-and-LUAD.sh](https://github.com/GeorgeBatch/TCGA-lung-histology-download/blob/main/0-download-LUSC-and-LUAD.sh) results in errors, try to generate new manifest files from the official portal.

I hope it helps!

**Comment by GeorgeBatch** [comment]
@bryanwong17, I just realised that the data portal (https://portal.gdc.cancer.gov/) has been updated, and some links in my README need to be updated. If you identify how to get the new manifests, please make a pull request.

**Comment by bryanwong17** [comment]
Hi @GeorgeBatch,

Doesn't the manifest file inside the [./tcga-download/](https://github.com/GeorgeBatch/TCGA-lung-histology-download/blob/main/tcga-download/) also contain the DSMIL dataset? My understanding is that after downloading from the manifest files, I just need to split it into train, validation, and test sets following the DSMIL work.

**Comment by GeorgeBatch** [comment]
You are absolutely right. The lung cancer dataset used in DSMIL was almost identical to TCGA-LUAD + TCGA-LUSC. The authors of DSMIL excluded ~10 corrupted images.

So after downloading you can follow the authors of DSMIL:
1. Exclude corrupted images.
2. Split into train and test.

**Comment by bryanwong17** [comment]
Got it, Thank you!

**Comment by bryanwong17** [comment]
Hi @GeorgeBatch , when I downloaded the manifest file from 2021-11-03, I could obtain 541 LUAD and 512 LUSC cases. However, when I tried to tile them into patches (even with a lower threshold), I could only get 1042 WSIs in total. Could you confirm whether you also obtained this amount? Thank you in advance!

**Comment by GeorgeBatch** [comment]
So it will depend what code you use for tiling. I used the [tiling code](https://github.com/binli123/dsmil-wsi/blob/master/deepzoom_tiler.py) from the DSMIL repository and did not have any problems with tiling as far as I can tell. Here were the slides I used for one of my works:

https://github.com/GeorgeBatch/dependency-mil/blob/main/labels/experiment-label-files/DETAILED_TCGA_LUAD_LUSC_BENIGN.csv

**Comment by bryanwong17** [comment]
Alright! However, when I checked the CSV file, it seems that the total number of WSIs used is 1046, not 1053 (541 LUAD + 512 LUSC as stated in the manifest file from 2021-11-03). Is this correct?

**Comment by GeorgeBatch** [comment]
Yes, I decided to exclude 7 slides following the DSMIL work:

https://github.com/GeorgeBatch/TCGA-lung-histology-download/?tab=readme-ov-file#corrupted-slides-excluded-in-dsmil-wsi-work

**Comment by bryanwong17** [comment]
Got it! I just have a simple follow-up question. From my understanding, one patient could have one or more WSIs, right? Also, what does 'case' mean in the TCGA NSCLC dataset?

**Comment by GeorgeBatch** [comment]
So here is a summary of what I gathered: https://github.com/GeorgeBatch/TCGA-lung-histology-download/?tab=readme-ov-file#tcga-lung-dataset

From what I understand, a tissue block extracted from one particular location of a patient’s lung correspond to a case. Every block can be sliced many times resulting in multiple slides per case. But sometimes, the same patient would have multiple tissue blocks extracted possibly at different times - they would form cases.

**Comment by bryanwong17** [comment]
Hi @GeorgeBatch. thanks for your answer! I will close this for now and let me know if I have further questions

**Comment by bryanwong17** [comment]
Hi @GeorgeBatch , sorry for asking again. After obtaining 1,046 WSIs (excluding 7 slides following the DSMIL work), what is the number of WSIs for training, validation, and testing? Could you provide detailed counts, including the number of LUAD and LUSC for each set?

If I am correct. you divided 1046 WSIs into 836 training and 210 testing (without validation). Is this correct?
